# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: run_scenario1
    steps:
      - task: TriggerBuild@3
        inputs:
          definitionIsInCurrentTeamProject: true
          buildDefinition: 'Scenario1'
          queueBuildForUserThatTriggeredBuild: true
          ignoreSslCertificateErrors: false
          useSameSourceVersion: false
          useCustomSourceVersion: false
          useSameBranch: true
          authenticationMethod: 'Personal Access Token'
          password: 'dd24zp7y5nhateu5yqf2nrtelldgvlw4i3egzd432zrzscplnjsa'
          waitForQueuedBuildsToFinish: true
          waitForQueuedBuildsToFinishRefreshTime: '60'
          failTaskIfBuildsNotSuccessful: true
          cancelBuildsIfAnyFails: false
          treatPartiallySucceededBuildAsSuccessful: false
          downloadBuildArtifacts: false
          storeInEnvironmentVariable: false
          enableBuildInQueueCondition: false
          dependentOnSuccessfulBuildCondition: false
          dependentOnFailedBuildCondition: false
          checkbuildsoncurrentbranch: false
          failTaskIfConditionsAreNotFulfilled: false
  - job: run_scenario2
    steps:
      - task: TriggerBuild@3
        inputs:
          definitionIsInCurrentTeamProject: true
          buildDefinition: 'Scenario2'
          queueBuildForUserThatTriggeredBuild: true
          ignoreSslCertificateErrors: false
          useSameSourceVersion: false
          useCustomSourceVersion: false
          useSameBranch: true
          password: 'dd24zp7y5nhateu5yqf2nrtelldgvlw4i3egzd432zrzscplnjsa'
          waitForQueuedBuildsToFinish: true
          waitForQueuedBuildsToFinishRefreshTime: '60'
          failTaskIfBuildsNotSuccessful: true
          cancelBuildsIfAnyFails: false
          treatPartiallySucceededBuildAsSuccessful: false
          downloadBuildArtifacts: false
          storeInEnvironmentVariable: false
          authenticationMethod: 'Personal Access Token'
          enableBuildInQueueCondition: false
          dependentOnSuccessfulBuildCondition: false
          dependentOnFailedBuildCondition: false
          checkbuildsoncurrentbranch: false
          failTaskIfConditionsAreNotFulfilled: false          