
trigger:
- none

pr:
- none

pool:
  vmImage: windows-2019

schedules:
- cron: "15 22 * * *" # cron syntax defining a schedule
  displayName: NightlyRun # friendly name given to a specific schedule
  always: true # whether to alway
  branches:
    include:
      - main

variables:
 - group: Nightly


stages:
#  - stage: ParseNightlyConfiguration
#    displayName: Parse Configuration for all nightly runs
#
#    jobs:
#      - job: ParseConfiguration
#ile czekac?
#jezeli nie ma regression to 2h
#jezeli nie ma deployment to 5h
#
#jezeli inactive to wogole odpusc
#
  - stage: QA
    displayName: Run cycle for QA
#    condition:  eq( variables['QAIsActive'], 'True')
    dependsOn: []
    jobs:
      - job: printer
        variables:
          parsedQANightlyDeployment:  $[variables.QANightlyDeployment]
        steps:
          - checkout: none
          - script: |
              echo "template expression"
              echo ${{variables.QANightlyRegression}}
              echo "macro expression"
              echo $(QANightlyDeployment)
              echo "runtime expression to macro"
              echo $(parsedQANightlyDeployment)

#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA"
#          #NightlyRegression: $(variables['QANightlyRegression'])
#          #NightlyDeployment: $(variables['QANightlyDeployment'])
#          #LSDigitalHubSiteCoreGitReference: $(variables['QABranchToDeployFrom'])
#          #LSDigitalHubAutoTestsGitReference: $(variables['QABranchToTestFrom'])
#          #NightlyRegression: ${{variables.QANightlyRegression}}
#          NightlyRegression: ${{  variables.QANightlyRegression  }}
#          NightlyDeployment: $(  QANightlyDeployment  )
#          LSDigitalHubSiteCoreGitReference: ${{variables.QABranchToDeployFrom}}
#          LSDigitalHubAutoTestsGitReference: ${{variables.QABranchToTestFrom}}
#  - stage: QA2
#    displayName: Run cycle for QA2
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA2"
#  - stage: QA3
#    displayName: Run cycle for QA3
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA3"
#  - stage: QA4
#    displayName: Run cycle for QA4
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA4"
#  - stage: QA5
#    displayName: Run cycle for QA5
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA5"
#  - stage: QA6
#    displayName: Run cycle for QA6
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA6"
#  - stage: QA7
#    displayName: Run cycle for QA7
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA7"
#  - stage: QA8
#    displayName: Run cycle for QA8
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA8"
#  - stage: QA9
#    displayName: Run cycle for QA9
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA9"
#  - stage: QA10
#    displayName: Run cycle for QA10
#    dependsOn: []
#    jobs:
#      - template: templates/Hermes.yml
#        parameters:
#          Environment: "DigitalHub-QA10"
#