
trigger:
- none

pr:
- none

pool:
  vmImage: windows-2019

#parameters:
#  - name: Configuration
#    displayName: configuration of a called pipeline
#    type: string
#    default: "{
#                 'resources': {
#                     'repositories': {
#                         'self': {
#                             'refName': 'refs/heads/main'
#                         }
#                     }
#                 },
#                 'templateParameters': {
#                     
#                 }
#             }"

stages:
  - stage: QA3
    displayName: Run cycle for QA3
    lockBehavior: sequential
    jobs:
      - job: dupa
        displayName: sdsdsd
        steps:
          - checkout: none
      - template: templates/Hermes.yml
        parameters:
          PipelineName: EnableEnv
          TimeToWait: 1
          Configuration: "{
                 'resources': {
                     'repositories': {
                         'self': {
                             'refName': 'refs/heads/main'
                         }
                     }
                 },
                 'templateParameters': {
                     'environment': 'DigitalHub-QA3'
                 }
             }"
      - template: templates/Hermes.yml
        parameters:
          PipelineName: Deployment
          TimeToWait: 1
          Configuration: "{
                 'resources': {
                     'repositories': {
                         'self': {
                             'refName': 'refs/heads/main'
                         }
                     }
                 },
                 'templateParameters': {
                     'environment': 'DigitalHub-QA3'
                 }
             }"
      - template: templates/Hermes.yml
        parameters:
          PipelineName: Regresion
          TimeToWait: 1
          Configuration: "{
                 'resources': {
                     'repositories': {
                         'self': {
                             'refName': 'refs/heads/main'
                         }
                     }
                 },
                 'templateParameters': {
                     'environment': 'DigitalHub-QA3'
                 }
             }"

