
trigger:
- none

pr:
- none

pool:
  vmImage: windows-2019

parameters:
  - name: PipelineName
    displayName: Name of the pipeline to call
    type: string
    default: Deployment
  - name: TimeToWait
    displayName: Time to wait before checking status of run
    type: string
    default: 1
  - name: Configuration
    displayName: configuration of a called pipeline
    type: string
    default: "{
                 'resources': {
                     'repositories': {
                         'self': {
                             'refName': 'refs/heads/main'
                         }
                     }
                 },
                 'templateParameters': {
                     'environment': 'DigitalHub-QA3'
                 }
             }"

stages:
  - stage: QA3
    displayName: Run cycle for QA3
    jobs:
      - template: templates/Hermes.yml
        parameters:
          PipelineName: EnableEnv
          TimeToWait: 1
          Configuration: "{
                 'resources': {
                     'repositories': {
                         'self': {
                             'refName': 'refs/heads/main'
                         }
                     }
                 },
                 'templateParameters': {
                     'environment': 'DigitalHub-QA3'
                 }
             }"