
trigger:
- none

pr:
- none

pool:
  vmImage: windows-2019


stages:
  - stage: QA
    displayName: Run cycle for QA
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA"
  - stage: QA2
    displayName: Run cycle for QA2
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA2"
  - stage: QA3
    displayName: Run cycle for QA3
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA3"
  - stage: QA4
    displayName: Run cycle for QA4
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA4"
  - stage: QA5
    displayName: Run cycle for QA5
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA5"
  - stage: QA6
    displayName: Run cycle for QA6
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA6"
  - stage: QA7
    displayName: Run cycle for QA7
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA7"
  - stage: QA8
    displayName: Run cycle for QA8
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA8"
  - stage: QA9
    displayName: Run cycle for QA9
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA9"
  - stage: QA10
    displayName: Run cycle for QA10
    lockBehavior: sequential
    jobs:
      - template: templates/hermes.yml
        parameters:
          Environment: "DigitalHub-QA10"
