
trigger:
- none

pr:
- none

pool:
  vmImage: windows-2019

#parameters:
#  - name: Configuration
#    displayName: configuration of a called pipeline
#    type: string
#    default: "{
#                 'resources': {
#                     'repositories': {
#                         'self': {
#                             'refName': 'refs/heads/main'
#                         }
#                     }
#                 },
#                 'templateParameters': {
#                     
#                 }
#             }"

stages:
  - stage: QA3
    displayName: Run cycle for QA3
    lockBehavior: sequential
    jobs:
      - job: InvokeAPI
        displayName: invoking api
        pool: Server
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'Pipelines_caller'
              method: 'POST'
              headers: |
                {
                "Authorization":"Basic ZW1hdHBpbDo0d200d3R3aGVnYTU1bWN6NG1tbW03cXcyY2VzeWVhZWduY2VkcHlhYnhvZXJod3ZnbGRh",
                "Content-Type":"application/json"
                }
              body: |
                {
                    'resources': {
                        'repositories': {
                            'self': {
                                'refName': 'refs/heads/main'
                            }
                        }
                    },
                    'templateParameters': {
                        'environment': 'DigitalHub-QA3',
                        "PlanId": "$(system.PlanId)"
                    }
                }
              urlSuffix: '/23/runs?api-version=6.0-preview.1'
              waitForCompletion: 'true'
#     - template: templates/Hermes.yml
#       parameters:
#         PipelineName: EnableEnv
#         TimeToWait: 1
#         Configuration: "{
#                'resources': {
#                    'repositories': {
#                        'self': {
#                            'refName': 'refs/heads/main'
#                        }
#                    }
#                },
#                'templateParameters': {
#                    'environment': 'DigitalHub-QA3'
#                }
#            }"
#     - template: templates/Hermes.yml
#       parameters:
#         PipelineName: Deployment
#         TimeToWait: 1
#         Configuration: "{
#                'resources': {
#                    'repositories': {
#                        'self': {
#                            'refName': 'refs/heads/main'
#                        }
#                    }
#                },
#                'templateParameters': {
#                    'environment': 'DigitalHub-QA3'
#                }
#            }"
#     - template: templates/Hermes.yml
#       parameters:
#         PipelineName: Regresion
#         TimeToWait: 1
#         Configuration: "{
#                'resources': {
#                    'repositories': {
#                        'self': {
#                            'refName': 'refs/heads/main'
#                        }
#                    }
#                },
#                'templateParameters': {
#                    'environment': 'DigitalHub-QA3'
#                }
#            }"

