
trigger:
- none

pr:
- none

pool:
  vmImage: windows-2019


stages:
  - stage: QA3
    displayName: Run cycle for QA3
    lockBehavior: sequential
    jobs:

      - job: InvokeAPI3
        displayName: Nightly process
        pool: Server
        steps:
          - task: InvokeRESTAPI@1
            displayName: Enable Environment
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'Pipelines_caller'
              method: 'POST'
              headers: |
                {
                "Authorization":"Basic ZW1hdHBpbDo0d200d3R3aGVnYTU1bWN6NG1tbW03cXcyY2VzeWVhZWduY2VkcHlhYnhvZXJod3ZnbGRh",
                "Content-Type":"application/json"
                }
              body: |
                {
                    'resources': {
                        'repositories': {
                            'self': {
                                'refName': 'refs/heads/main'
                            }
                        }
                    },
                    'templateParameters': {
                        'environment': 'DigitalHub-QA3'
                    }
                    "variables": {
                      "PlanUrl": {"isSecret":"false" ,"value": "$(system.CollectionUri)"},
                      "ProjectId": {"isSecret":"false" ,"value":"$(system.TeamProjectId)"},
                      "HubName": {"isSecret":"false" ,"value":"$(system.HostType)"},
                      "PlanId": {"isSecret":"false" ,"value":"$(system.PlanId)"},
                      "JobId": {"isSecret":"false" ,"value":"$(system.JobId)"},
                      "TimelineId": {"isSecret":"false" ,"value":"$(system.TimelineId)"},
                      "TaskInstanceId": {"isSecret":"false" ,"value":"$(system.TaskInstanceId)"}
                    }
                }
              urlSuffix: '/23/runs?api-version=6.0-preview.1'
              waitForCompletion: 'true'
          - task: InvokeRESTAPI@1
            displayName: Run Deployment
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'Pipelines_caller'
              method: 'POST'
              headers: |
                {
                "Authorization":"Basic ZW1hdHBpbDo0d200d3R3aGVnYTU1bWN6NG1tbW03cXcyY2VzeWVhZWduY2VkcHlhYnhvZXJod3ZnbGRh",
                "Content-Type":"application/json"
                }
              body: |
                {
                    'resources': {
                        'repositories': {
                            'self': {
                                'refName': 'refs/heads/main'
                            }
                        }
                    },
                    'templateParameters': {
                        'environment': 'DigitalHub-QA3'
                    }
                    "variables": {
                      "PlanUrl": {"isSecret":"false" ,"value": "$(system.CollectionUri)"},
                      "ProjectId": {"isSecret":"false" ,"value":"$(system.TeamProjectId)"},
                      "HubName": {"isSecret":"false" ,"value":"$(system.HostType)"},
                      "PlanId": {"isSecret":"false" ,"value":"$(system.PlanId)"},
                      "JobId": {"isSecret":"false" ,"value":"$(system.JobId)"},
                      "TimelineId": {"isSecret":"false" ,"value":"$(system.TimelineId)"},
                      "TaskInstanceId": {"isSecret":"false" ,"value":"$(system.TaskInstanceId)"}
                    }
                }
              urlSuffix: '/24/runs?api-version=6.0-preview.1'
              waitForCompletion: 'true'
          - task: InvokeRESTAPI@1
            displayName: Run Regression
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'Pipelines_caller'
              method: 'POST'
              headers: |
                {
                "Authorization":"Basic ZW1hdHBpbDo0d200d3R3aGVnYTU1bWN6NG1tbW03cXcyY2VzeWVhZWduY2VkcHlhYnhvZXJod3ZnbGRh",
                "Content-Type":"application/json"
                }
              body: |
                {
                    'resources': {
                        'repositories': {
                            'self': {
                                'refName': 'refs/heads/main'
                            }
                        }
                    },
                    'templateParameters': {
                        'environment': 'DigitalHub-QA3'
                    }
                    "variables": {
                      "PlanUrl": {"isSecret":"false" ,"value": "$(system.CollectionUri)"},
                      "ProjectId": {"isSecret":"false" ,"value":"$(system.TeamProjectId)"},
                      "HubName": {"isSecret":"false" ,"value":"$(system.HostType)"},
                      "PlanId": {"isSecret":"false" ,"value":"$(system.PlanId)"},
                      "JobId": {"isSecret":"false" ,"value":"$(system.JobId)"},
                      "TimelineId": {"isSecret":"false" ,"value":"$(system.TimelineId)"},
                      "TaskInstanceId": {"isSecret":"false" ,"value":"$(system.TaskInstanceId)"}
                    }
                }
              urlSuffix: '/25/runs?api-version=6.0-preview.1'
              waitForCompletion: 'true'


#     - template: templates/Hermes.yml
#       parameters:
#         PipelineName: EnableEnv
#         TimeToWait: 1
#         Configuration: "{
#                'resources': {
#                    'repositories': {
#                        'self': {
#                            'refName': 'refs/heads/main'
#                        }
#                    }
#                },
#                'templateParameters': {
#                    'environment': 'DigitalHub-QA3'
#                }
#            }"
#     - template: templates/Hermes.yml
#       parameters:
#         PipelineName: Deployment
#         TimeToWait: 1
#         Configuration: "{
#                'resources': {
#                    'repositories': {
#                        'self': {
#                            'refName': 'refs/heads/main'
#                        }
#                    }
#                },
#                'templateParameters': {
#                    'environment': 'DigitalHub-QA3'
#                }
#            }"
#     - template: templates/Hermes.yml
#       parameters:
#         PipelineName: Regresion
#         TimeToWait: 1
#         Configuration: "{
#                'resources': {
#                    'repositories': {
#                        'self': {
#                            'refName': 'refs/heads/main'
#                        }
#                    }
#                },
#                'templateParameters': {
#                    'environment': 'DigitalHub-QA3'
#                }
#            }"

