# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
- none
pool:
  vmImage: windows-latest

parameters:
  - name: environment
    default: DigitalHub-QA
    values: 
      - DigitalHub-QA
      - DigitalHub-QA2
      - DigitalHub-QA3
      - DigitalHub-QA4
      - DigitalHub-QA5
      - DigitalHub-QA6
      - DigitalHub-QA7
      - DigitalHub-QA8
      - DigitalHub-QA9
      - DigitalHub-QA10


stages:
  - stage: DeployQAEnvironment
    displayName: "Deploy QA Environment"
    jobs:
          - job: DeployDHQA
            displayName: "Deploy DH"
            timeoutInMinutes: 15
            steps:
              - checkout: none
              - task: PowerShell@2
                displayName: 'This is the deployment pipeline for ${{parameters.environment}}'
                inputs:
                  targetType: 'inline'
                  script: |
                    echo Hello, world!
                    write-host ${{parameters.environment}}
                    write-host "<<<<<<<<<<<<<<<<<"
                    if ( "${{parameters.environment}}" -eq "DigitalHub-QA") {
                       Write-Host "##vso[task.complete result=Failed;]" 
                       Write-host "mamy error!"
                       write-host  ""
                    }
                    # i tu mamy trigerowanie octopusa 2 warianty (sucess lub failure)
          - job: WaitForOctopus
            dependsOn: DeployDHQA
            timeoutInMinutes: 300
            variables:
                WaitTime: $[ dependencies.DeployDHQA.outputs['TriggerDeploymentTask.WaitTime'] ]
            pool: Server
            steps:
              - task: Delay@1
                inputs:
                  delayForMinutes: 1
          - job: CheckStatus
            dependsOn: [ WaitForOctopus, DeployDHQA ]
            condition: always()
            timeoutInMinutes: 25
            variables:
                DeploymentTaskId: $[ dependencies.DeployDHQA.outputs['TriggerDeploymentTask.DeploymentTaskId'] ]
                DeployDHQAStatus: $[ dependencies.DeployDHQA.result ]
            steps:
              - checkout: none
              - task: PowerShell@2
                displayName: "check deployment status in Octopus"
                inputs:
                  targetType: 'inline'
                  script: |
                    $ErrorActionPreference = "Stop"
                    Write-Host "the result of DeployDHQA job WAS $(DeployDHQAStatus)"
              - template: templates/callback.yml

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    #echo "##vso[task.complete result=Failed;]"
#    sleep 10
#  displayName: 'Run a multi-line script'
