# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
- none
pool:
  vmImage: windows-latest

parameters:
  - name: environment
    default: DigitalHub-QA
    values: 
      - DigitalHub-QA
      - DigitalHub-QA2
      - DigitalHub-QA3
      - DigitalHub-QA4
      - DigitalHub-QA5
      - DigitalHub-QA6
      - DigitalHub-QA7
      - DigitalHub-QA8
      - DigitalHub-QA9
      - DigitalHub-QA10

steps:
- script: echo Hello, world!
  displayName: 'This is the deployment pipeline for ${{parameters.environment}}'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    #echo "##vso[task.complete result=Failed;]"
    sleep 10
  displayName: 'Run a multi-line script'
- template: templates/callback.yml