# Internal pipeline that is also independent

#Trigger must be none (default is main and it would trigger CI jobs)
trigger:
- none

#TODO not sure if generic agents will suffice
pool: 'ematpil'

parameters:
  - name: inerparam
    displayName: inerparam
    type: string
    default: inerparam-default



steps:
- script: Running Inerpipe

- script: |
    echo Start parameter
    echo ${{parameters.inerparam}}
    echo End parameter
