
parameters:
  - name: inerparam
    displayName: inerparam
    type: string
    default: inerparam-default


stages:
  - stage: InerStage
    jobs:
      - job: InerJob
        steps:
          - checkout: dupa2
          - script: echo Running Inerpipe
          - script: |
              echo Start parameter
              echo ${{parameters.inerparam}}
              echo End parameter
