
resources:
 repositories:
   - repository: dupa2
     type: github
     endpoint: Poncjuszon
     name: Poncjuszon/Azure_pipelines
     ref: dupa

parameters:
  - name: inerparam
    displayName: inerparam
    type: string
    default: inerparam-default


stages:
  - stage: InerStage
    jobs:
      - job: InerJob
        steps:
          - script: echo Running Inerpipe
          - script: |
              echo Start parameter
              echo ${{parameters.inerparam}}
              echo End parameter
