# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
#
#
trigger: none

pool:
  vmImage: 'windows-latest'



steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 5.0.102
    installationPath: $(Agent.ToolsDirectory)/dotnet

#- task: NuGetToolInstaller@1


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'myWebApp/myWebApp.csproj'
    arguments: '-c Release --output $(System.ArtifactsDirectory) --runtime win-x64'
    zipAfterPublish: true

- publish: $(System.ArtifactsDirectory)
  artifact: drop

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    artifactName: drop
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Private subscription(0b6d9a4b-556d-4dab-bd4a-e5f78006033d)'
    appType: 'webApp'
    WebAppName: 'testApp12377'
    deployToSlotOrASE: true
    ResourceGroupName: 'AppService'
    SlotName: 'Standby'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'




