# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0
- task: PowerShell@2
  displayName: 'backmerge to develop'
  inputs:
    targetType: 'inline'
    script: |
      write-host "============ error action control==================================="
      #$ErrorActionPreference = "Stop"
      
      write-host "===================pull for latests changes first time============================"
      git fetch origin develop
      git pull
      write-host "=========list branches ======================================"
      git branch -r
      write-host "=================checkout develop=============================="
      git checkout develop
      write-host "===================pull for latests changes secondtime============================"
      git pull
      write-host "====================show status==========================="
      git status
      write-host "================try to merge==============================="
      git merge origin/release/v2023.1.0
      write-host "=================show git log=============================="
      git log | Select-Object -first 20
      write-host "==============================================="

