# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: 'backmerge to develop'
  inputs:
    targetType: 'inline'
    script: |
      write-host "==============================================="
      #$ErrorActionPreference = "Stop"
      write-host "==============================================="
      git pull
      write-host "==============================================="
      git branch -r
      write-host "==============================================="
      git checkout develop
      write-host "==============================================="
      git status
      write-host "==============================================="
      git merge origin/release/v2023.1.0
      write-host "==============================================="
      git log | Select-Object -first 20
      write-host "==============================================="

