# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pr:
- none

pool:
  vmImage: windows-latest

variables:
 - group: hermes

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0
- task: PowerShell@2
  displayName: 'backmerge to develop'
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = "Stop"
      $currentRelease = "$(Build.SourceBranchName)".replace("v","")
      Write-Host "Porting changes from release $currentRelease >>>>>>>>>>>>>>>"
      git checkout "$(Build.SourceBranch)".replace("refs/heads/","")
      $releases = git branch  --list --remote origin/release/v* | % { $_.replace("origin/release/v","").trim() } | Sort-Object {[System.Version]$_}
      #$currentReleaseIndex = $releases.IndexOf($currentRelease)
      #$nextReleaseIndex = $currentReleaseIndex +1
      $nextRelease = $releases[$releases.IndexOf($currentRelease) + 1]
      if ($nextRelease -eq $null) {
        $nextRelease = "develop"
      } else {
        Write-Host "Merge to $nextRelease"
      }
      Write-Host "Porting changes to $currentRelease <<<<<<<<<<<<<<<"
      $env:GH_TOKEN = "$(GH_TOKEN)"
      gh pr create --base release/v$nextRelease --title "Automerge from release/v$currentRelease to release/v$nextRelease" --body "Porting fixes to all newer releases"
      write-host "last command result $?"
      Write-Host "PR Opened"
      sleep 10
      gh pr list 


