# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pr:
- none

pool:
  vmImage: windows-latest

variables:
 - group: hermes

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0
- task: PowerShell@2
  displayName: 'ReleaseAutoMerge'
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = "Stop"
      $env:GH_TOKEN = "$(GH_TOKEN)"

      $currentReleaseSemVer = "$(Build.SourceBranchName)".replace("v","")
      git checkout release/v$currentReleaseSemVer
      $releasesSemVer = git branch  --list --remote origin/release/v* | % { $_.replace("origin/release/v","").trim() } | Sort-Object {[System.Version]$_}
      $nextReleaseSemVer = $releasesSemVer[$releasesSemVer.IndexOf($currentReleaseSemVer) + 1]
      if ($nextReleaseSemVer -eq $null) { $nextRelease = "develop" } else { $nextRelease = "release/v" + $nextReleaseSemVer }

      Write-Host "Porting changes from release $currentReleaseSemVer to $nextRelease"
      $PrTitle = "Automerge from release/v$currentReleaseSemVer to $nextRelease"
      gh pr create --base $nextRelease --title "$PrTitle" --body "Porting fixes to newer release/develop" --reviewer $(AutoMergeReviewers)
      If ($? -ne $true) {
          Write-Host "##vso[task.logissue type=warning;] Failed to create PR, see details above" 
          Write-Host "##vso[task.complete result=SucceededWithIssues;]"
          Exit 0
      } else {
          Write-Host "PR has been opened"
      }
