# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Running after merge to release only to back merge to develop and all other releases created afterwards'

- script: |
    $ErrorActionPreference = "Stop"
    git checkout develop
    git merge origin/release/v2023.1.0
    git log | Select-Object -first 10
  displayName: 'backmerge to develop'
