# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: scenario1
    default: true
    type: boolean
  - name: scenario2
    default: true
    type: boolean
  - name: environment
    displayName: Environment
    type: string
    default: DigitalHub-INT
    values:
      - DigitalHub-INT
      - DigitalHub-QA
      - DigitalHub-UAT
      - DigitalHub-PROD



jobs:
  - job: Master
    displayName: 'Running MASTER'
    strategy:
     parallel: 2
    steps: 
      - script: echo Hello from Master!
  - ${{ if eq(parameters.scenario1, true) }}:
    - template: azure-scenario1.yml
  - ${{ if eq(parameters.scenario2, true) }}:
    - template: azure-scenario2.yml

#strategy:
# maxParallel: 2
#steps:
#- script: echo Hello, from Master!
#  displayName: 'Running MASTER'
#- ${{ if eq(parameters.scenario1, true) }}:
#  - template: azure-scenario1.yml
#    parameters:
#      dupa: true
#- ${{ if eq(parameters.scenario2, true) }}:
#  - template: azure-scenario2.yml

